package com.sentinq.trust;

// TrustDimension.java

public enum TrustDimension {
    MERCHANT_LEGITIMACY,

    PRODUCT_QUALITY,
    PRODUCT_ACCURACY,
    PRODUCT_DURABILITY,

    FULFILLMENT_RELIABILITY,
    DELIVERY_ACCURACY,

    RETURNS_RELIABILITY,
    REFUND_RELIABILITY,
    CUSTOMER_REMEDIATION,

    COMMUNITY_REPUTATION,

    TRANSACTION_INTEGRITY
}