package com.sentinq.audit;

public enum AuditEventType {
    REQUEST_RECEIVED,
    PRINCIPAL_LOADED,
    AGENT_SELECTED,
    DELEGATION_VALIDATED,
    PREFERENCES_LOADED,
    GOAL_INTERPRETED,
    MANDATE_CREATED,
    SEARCH_REQUEST_SENT,
    CANDIDATES_RECEIVED,
    CANDIDATES_RESOLVED,
    FINAL_DECISION,
    ORCHESTRATION_FAILED
}